package com.rfpe.estimator.model;

public enum ResourceType {
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    BACKEND_LEAD,
    FRONTEND_LEAD,
    QA_ENGINEER,
    QA_LEAD,
    BUSINESS_ANALYST,
    PROJECT_MANAGER,
    UX_DESIGNER,
    TECHNICAL_ARCHITECT,
    DEVOPS_ENGINEER,
    DEVOPS_LEAD
}
